//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsertarPedimentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imex_Container
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Imex_Container()
        {
            this.Imex_Info_EntregaAduana = new HashSet<Imex_Info_EntregaAduana>();
        }
    
        public int ContainerId { get; set; }
        public string Container { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imex_Info_EntregaAduana> Imex_Info_EntregaAduana { get; set; }
    }
}
