//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsertarPedimentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imex_Terminal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Imex_Terminal()
        {
            this.Imex_Info_EntregaAduana = new HashSet<Imex_Info_EntregaAduana>();
        }
    
        public int TerminalId { get; set; }
        public string Descripcion { get; set; }
        public string Codigo { get; set; }
        public string Splc { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> Interpacifico { get; set; }
        public Nullable<int> horas { get; set; }
        public Nullable<int> horaDiferencia { get; set; }
        public string EmailOperaciones { get; set; }
        public Nullable<bool> AceptaCambioPatio { get; set; }
        public bool GeneraPedido { get; set; }
        public Nullable<int> Maritimo { get; set; }
        public Nullable<bool> ATR { get; set; }
        public Nullable<bool> Intermodal { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public string RutaServerLocal { get; set; }
        public Nullable<bool> Remolques { get; set; }
        public Nullable<bool> Trasvase { get; set; }
        public string SegmentoRed { get; set; }
        public Nullable<bool> SIMEXPRO { get; set; }
        public Nullable<bool> SIMEX_API { get; set; }
        public Nullable<int> MaxContainers { get; set; }
        public Nullable<int> TiempoRecoleccion { get; set; }
        public Nullable<int> Almacenaje { get; set; }
        public Nullable<bool> Sidopla { get; set; }
        public bool SIDOPLAFiltradoCrossBorderSPLC { get; set; }
        public bool CargaMasivaSidopla { get; set; }
        public bool ValidaSoloContenedoresSidopla { get; set; }
        public Nullable<bool> EnviaSAPMyR { get; set; }
        public Nullable<bool> ConsultaMaterialesSAPMyR { get; set; }
        public Nullable<bool> Recarga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imex_Info_EntregaAduana> Imex_Info_EntregaAduana { get; set; }
    }
}
