//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsertarPedimentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imex_Info_EntregaAduana
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Imex_Info_EntregaAduana()
        {
            this.Imex_Info_EntregaAduana_Pedimentos = new HashSet<Imex_Info_EntregaAduana_Pedimentos>();
        }
    
        public int InfoEntregaId { get; set; }
        public Nullable<int> EntregaId { get; set; }
        public Nullable<int> ContainerId { get; set; }
        public Nullable<int> TranTypeId { get; set; }
        public string ImpoExpo { get; set; }
        public string Entry { get; set; }
        public string Guia { get; set; }
        public string LiberoAduana { get; set; }
        public Nullable<System.DateTime> FechaLiberado { get; set; }
        public string SalioTren { get; set; }
        public string SalioPuerta { get; set; }
        public Nullable<System.DateTime> UltimoModificado { get; set; }
        public string DocEntrega { get; set; }
        public string BL { get; set; }
        public string Regimen { get; set; }
        public string Pedimento { get; set; }
        public string DescripcionMercancia { get; set; }
        public string ValorComercial { get; set; }
        public string PesoMercancia { get; set; }
        public string UM { get; set; }
        public string Bultos { get; set; }
        public string UM_Bultos { get; set; }
        public string FechaEntregaTransito { get; set; }
        public string NumeroPatenteAA { get; set; }
        public string ClavePedimento { get; set; }
        public string FechaCierreTransito { get; set; }
        public string PrimerPuertoEmbarque { get; set; }
        public string ProveedorMercancia { get; set; }
        public string DireccionProveedor { get; set; }
        public string ENTRYNumber { get; set; }
        public string NIUNumber { get; set; }
        public string Sellos { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public string RampaOrigen { get; set; }
        public string EscapeOrigen { get; set; }
        public string RampaDestino { get; set; }
        public string EscapeDestino { get; set; }
        public string RutaFerroviaria { get; set; }
        public string PuntoIntercambio { get; set; }
        public string Seleccion { get; set; }
        public string NumeroFactura { get; set; }
        public string FechaRetorno { get; set; }
        public string DestinoRetorno { get; set; }
        public string FechaConfiscado { get; set; }
        public string Desconsolidado { get; set; }
        public string Consolidado { get; set; }
        public string LlenoVacio { get; set; }
        public string Peso { get; set; }
        public string Piezas { get; set; }
        public string Unidad { get; set; }
        public string SellosSalida { get; set; }
        public string EstatusAduanal { get; set; }
        public string PlataformaSalida { get; set; }
        public string ReferenciaCliente { get; set; }
        public string ComentariosPedimento { get; set; }
        public string Posicion { get; set; }
        public string UMPeso { get; set; }
        public string FechaAvisoAbandono { get; set; }
        public string ObservacionActaEntrega { get; set; }
        public string InfRelMcia { get; set; }
        public string ComentariosPlanCarga { get; set; }
        public string Consignatario { get; set; }
        public string TipoContenedor { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaManiobra { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public Nullable<int> Estadia { get; set; }
        public Nullable<int> Almacenaje { get; set; }
        public string EmpresaTransferencia { get; set; }
        public Nullable<System.DateTime> FechaTransferencia { get; set; }
        public string PedimentoSalida { get; set; }
        public string NumeroPatenteSalida { get; set; }
        public string ClavePedimentoSalida { get; set; }
        public Nullable<System.DateTime> FechaEscritura { get; set; }
        public Nullable<int> TerminalId { get; set; }
        public string DomicilioConsignatario { get; set; }
        public string TipoManiobra { get; set; }
        public string ClaseManiobra { get; set; }
        public string Facturatario { get; set; }
        public Nullable<bool> EdiGenerado { get; set; }
        public string AgenteAduanal { get; set; }
        public string FechaDestinoRetorno { get; set; }
        public Nullable<System.DateTime> FechaAbandono { get; set; }
        public Nullable<System.DateTime> FechaManiobraAnden { get; set; }
        public string FolioCFDI { get; set; }
        public string MontoCFDI { get; set; }
        public string MontoAlmacenaje { get; set; }
        public string CompensacionAlmacenaje { get; set; }
        public string MciaAsignadoAduana { get; set; }
        public string OficioAduana { get; set; }
        public string OficioAduanaFisco { get; set; }
        public string AlmacenajeASolicitud { get; set; }
        public string VolumenMercancia { get; set; }
        public Nullable<int> IdCatPuertoAduana { get; set; }
        public string UserName { get; set; }
        public string UserNameHR { get; set; }
        public Nullable<System.DateTime> FechaHR { get; set; }
        public Nullable<bool> HR { get; set; }
        public string UserNameCT { get; set; }
        public Nullable<System.DateTime> FechaCT { get; set; }
        public string Comentarios { get; set; }
    
        public virtual Imex_Container Imex_Container { get; set; }
        public virtual Imex_Terminal Imex_Terminal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imex_Info_EntregaAduana_Pedimentos> Imex_Info_EntregaAduana_Pedimentos { get; set; }
    }
}
