//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigracionPedimentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imex_Info_EntregaAduana_Pedimentos
    {
        public long PedimentoId { get; set; }
        public int InfoEntregaId { get; set; }
        public string Anio { get; set; }
        public string CodigoDespacho { get; set; }
        public string NumeroPedimento { get; set; }
        public string ClavePedimento { get; set; }
        public string Remesa { get; set; }
        public string TipoPedimento { get; set; }
        public Nullable<bool> ProcesadoTMS { get; set; }
        public Nullable<System.DateTime> FechaProcesadoTMS { get; set; }
        public bool Activo { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<long> EnvioPedimentosId { get; set; }
    
        public virtual Imex_Info_EntregaAduana Imex_Info_EntregaAduana { get; set; }
    }
}
